.TH DISKTEST "1" "2008-09-04" "FGDiag" "User Commands"
.SH NAME
disktest - Tests hard drives, and wipes them if they work
.SH SYNOPSIS
.BR disktest
.SH DESCRIPTION
Disktest runs a smart test, checks for bad blocks, and wipes the disk if it works.
.SH NOTES
Disktest complies to DOD 5220-22.M standards for data destruction.
See http://wiki.freegeek.org/index.php/Data_Security for more information.
