#!/usr/bin/env python

__version__ = '$Revision$'[11:-2]

from os import path
import sys

from fgdiag.disk import diskdiag
from fgdiag.disk import badblocks, disk
from fgdiag import disk as diskPackage


def ident(dev):
    if dev == "/dev/hda":
        return {'serialNo': 'AAAAA',
                'model': "a drive"}
    else:
        return {'serialNo': 'BBBBB',
                'model': "b drive"}        

def size(dev):
    if dev == "/dev/hda":
        return 1024*1024*1024*2 # 2 GB
    else:
        return 1024*1024*1024*4 # 4 GB
thisdir = path.dirname(diskPackage.__file__)

badblocks.BADBLOCKS = path.join(thisdir, "fauxblocks")
badblocks.Badblocks.path = badblocks.BADBLOCKS
disk.list_mounted_devices = lambda : []
disk.findDrivesToScan = lambda : [ '/dev/hda', '/dev/hdb' ]
disk.identification = ident
disk.getDeviceSize = size

if __name__ == "__main__":
    diskdiag.DiskDiag().start_test()
