#!/usr/bin/env python2.2

__version__ = '$Revision$'[11:-2]

from os import path
import sys

from fgdiag.disk import diskdiag
from fgdiag.disk import badblocks, disk
from fgdiag import disk as diskPackage

SECTOR_COUNT = 2 * (1024**2) # 2 GB

thisdir = path.dirname(diskPackage.__file__)

badblocks.BADBLOCKS = path.join(thisdir, "fauxblocks")
badblocks.Badblocks.path = badblocks.BADBLOCKS
disk.list_mounted_devices = lambda : []
disk.findDrivesToScan = lambda : [ '/dev/hda', '/dev/hdb' ]
disk.identification = lambda a: {'serialNo': 'FAUX-%s' % (a,),
                                 'model': 'Imaginary Hardware'}
disk.getDeviceSize = lambda a: SECTOR_COUNT * 1024

if __name__ == "__main__":
    diskdiag.DiskDiag().start_test()
